title: LAThomson
description: Personal website of Louis Cooper-Thomson — technical AI safety researcher.
tagline: my personal website!

picture: /assets/img/profile_picture.png

permalink: /blog/:slug/
